# -*- coding: utf-8 -*-
"""Dashboard Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MBKHoTXW-ZDlWBjwPsACoAvWt3whyR9
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# =========================
# CONFIG
# =========================
st.set_page_config(page_title="Shipping Cost Dashboard", layout="wide")

st.title("Shipping Cost Analysis Dashboard")

# =========================
# LOAD DATA
# =========================
df = pd.read_csv('df_final.csv')

# =========================
# SIDEBAR FILTER
# =========================
st.sidebar.header("Filter Data")

selected_states = st.sidebar.multiselect(
    "Pilih Wilayah",
    df['customer_state'].unique(),
    default=df['customer_state'].unique()
)

df = df[df['customer_state'].isin(selected_states)]

# =========================
# METRICS
# =========================
st.subheader("Ringkasan")

col1, col2, col3 = st.columns(3)

col1.metric("Avg Ongkir", round(df['freight_value'].mean(),2))
col2.metric("Avg Harga", round(df['price'].mean(),2))
col3.metric("Total Transaksi", len(df))

# =========================
# PERTANYAAN 1
# =========================
st.header("Faktor Penyebab Ongkir Tinggi")

col1, col2 = st.columns(2)

# Scatter Plot
with col1:
    st.subheader("Harga vs Ongkir")
    fig, ax = plt.subplots()
    sns.scatterplot(data=df, x='price', y='freight_value', alpha=0.3, ax=ax)
    st.pyplot(fig)

# Ratio Distribution
with col2:
    df['freight_ratio'] = df['freight_value'] / df['price']
    st.subheader("Distribusi Rasio Ongkir")
    fig2, ax2 = plt.subplots()
    sns.histplot(df['freight_ratio'], bins=50, ax=ax2)
    st.pyplot(fig2)

# Bar Chart Wilayah
st.subheader("Rata-rata Ongkir per Wilayah")

df_state = df.groupby('customer_state')['freight_value'].mean().sort_values(ascending=False)

fig3, ax3 = plt.subplots(figsize=(10,4))
df_state.plot(kind='bar', ax=ax3)
plt.xticks(rotation=45)

st.pyplot(fig3)

st.write("Insight: Ongkir lebih dipengaruhi oleh wilayah dibandingkan harga produk.")

# =========================
# PERTANYAAN 2
# =========================
st.header("Analisis Ongkir per Wilayah")

# Bar Chart Ranking
st.subheader("Ranking Wilayah berdasarkan Rata-rata Ongkir")

fig4, ax4 = plt.subplots(figsize=(10,4))
df_state.plot(kind='bar', ax=ax4)
plt.xticks(rotation=45)

st.pyplot(fig4)

# Boxplot Top & Bottom
top5 = df_state.head(5).index
bottom5 = df_state.tail(5).index

selected = list(top5) + list(bottom5)

df_box = df[df['customer_state'].isin(selected)]

st.subheader("Distribusi Ongkir (Top & Bottom Wilayah)")

fig5, ax5 = plt.subplots()
sns.boxplot(data=df_box, x='customer_state', y='freight_value', ax=ax5)

st.pyplot(fig5)

st.write("Insight: Wilayah tertentu memiliki ongkir lebih tinggi akibat faktor geografis dan efisiensi distribusi.")