# -*- coding: utf-8 -*-
"""Dashboard Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MBKHoTXW-ZDlWBjwPsACoAvWt3whyR9
"""
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# =========================
# CONFIG
# =========================
st.set_page_config(page_title="E-Commerce Analysis Dashboard", layout="wide")

st.title("📦 E-Commerce Data Analysis Dashboard")

# =========================
# LOAD DATA
# =========================
df_final = pd.read_csv('df_final.csv')

# =========================
# FEATURE ENGINEERING
# =========================
df_final['freight_ratio'] = df_final['freight_value'] / df_final['price']
df_final['revenue'] = df_final['price']

# =========================
# SIDEBAR
# =========================
st.sidebar.header("Filter")

selected_states = st.sidebar.multiselect(
    "Pilih Wilayah",
    options=df_final['customer_state'].unique(),
    default=df_final['customer_state'].unique()
)

df = df_final[df_final['customer_state'].isin(selected_states)]

# =========================
# METRICS
# =========================
st.subheader("📊 Ringkasan")

col1, col2, col3 = st.columns(3)

col1.metric("Avg Ongkir", round(df['freight_value'].mean(), 2))
col2.metric("Avg Harga", round(df['price'].mean(), 2))
col3.metric("Total Transaksi", len(df))

# =========================
# PERTANYAAN 1
# =========================
st.header("📍 Analisis Faktor Ongkir")

# 1. Regression Plot
st.subheader("Hubungan Harga vs Ongkir")

fig1, ax1 = plt.subplots()
sns.regplot(
    data=df,
    x='price',
    y='freight_value',
    scatter_kws={'alpha':0.3},
    ax=ax1
)
st.pyplot(fig1)

# 2. Freight Ratio per Wilayah
st.subheader("Rata-rata Rasio Ongkir per Wilayah")

ratio_state = df.groupby('customer_state')['freight_ratio'].mean().sort_values(ascending=False)

fig2, ax2 = plt.subplots(figsize=(10,4))
sns.barplot(x=ratio_state.index, y=ratio_state.values, ax=ax2)

plt.xticks(rotation=45)
st.pyplot(fig2)

# 3. Scatter by Wilayah
st.subheader("Distribusi Ongkir berdasarkan Wilayah")

fig3, ax3 = plt.subplots()
sns.scatterplot(
    data=df,
    x='price',
    y='freight_value',
    hue='customer_state',
    alpha=0.5,
    legend=False,
    ax=ax3
)
st.pyplot(fig3)

# 4. Top 5 Wilayah
st.subheader("Top 5 Wilayah")

top_states = df['customer_state'].value_counts().head(5).index
df_top = df[df['customer_state'].isin(top_states)]

fig4, ax4 = plt.subplots()
sns.scatterplot(
    data=df_top,
    x='price',
    y='freight_value',
    hue='customer_state',
    alpha=0.6,
    ax=ax4
)
st.pyplot(fig4)

# =========================
# PERTANYAAN 2
# =========================
st.header("📦 Analisis Produk")

# Top Produk Terlaris
st.subheader("Top 10 Produk Terlaris")

top_products = (
    df.groupby('product_id')['order_item_id']
    .count()
    .sort_values(ascending=False)
    .head(10)
)

fig5, ax5 = plt.subplots(figsize=(10,4))
top_products.plot(kind='bar', ax=ax5)
plt.xticks(rotation=45)

st.pyplot(fig5)

# Top Revenue
st.subheader("Top 10 Produk dengan Revenue Tertinggi")

top_revenue = (
    df.groupby('product_id')['revenue']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

fig6, ax6 = plt.subplots(figsize=(10,4))
top_revenue.plot(kind='bar', ax=ax6)
plt.xticks(rotation=45)

st.pyplot(fig6)

# Pareto Chart
st.subheader("Pareto Produk Terlaris")

product_sales = (
    df.groupby('product_id')['order_item_id']
    .count()
    .sort_values(ascending=False)
)

top10 = product_sales.head(10)
cum_percentage = top10.cumsum() / top10.sum() * 100

fig7, ax1 = plt.subplots(figsize=(10,4))

top10.plot(kind='bar', ax=ax1)
ax1.set_ylabel('Jumlah Terjual')

ax2 = ax1.twinx()
ax2.plot(cum_percentage.values, marker='o')
ax2.set_ylabel('Persentase Kumulatif (%)')

plt.xticks(rotation=45)

st.pyplot(fig7)

# =========================
# KESIMPULAN
# =========================
st.header("📌 Kesimpulan")

st.write("""
Penjualan didominasi oleh beberapa produk terlaris yang berkontribusi besar terhadap jumlah transaksi. 
Namun, produk dengan revenue tertinggi tidak selalu merupakan produk yang paling sering dibeli, melainkan cenderung berasal dari produk dengan harga lebih tinggi. 
Selain itu, biaya pengiriman lebih dipengaruhi oleh faktor wilayah dibandingkan harga produk, yang menunjukkan adanya perbedaan efisiensi distribusi antar wilayah.

Strategi bisnis yang disarankan adalah menjaga ketersediaan produk terlaris untuk mempertahankan volume penjualan, 
serta mengoptimalkan produk dengan revenue tinggi melalui strategi upselling dan promosi. 
Kombinasi keduanya dapat meningkatkan pendapatan secara optimal.
""")
